version: '3.8'
services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  web:
    build: .
    ports:
      - '80:3000'
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
